# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(max_length=30)),
                ('course_subject', models.CharField(choices=[('M', 'Math'), ('S', 'Science'), ('E', 'English'), ('H', 'History'), ('E', 'Elective')], default='E', max_length=3)),
                ('student', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
